#!/usr/bin/python3
import sys
sys.path.append("..")
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
from doord import app

http_server = HTTPServer(WSGIContainer(app))
http_server.listen(5000, address=[YOUR-LOCAL-SERVER-IP])
IOLoop.instance().start()
